// Generated by CoffeeScript 1.6.3
(function() {
  var node, parseOrgMode, test;

  parseOrgMode = require('./org.coffee').parseOrgMode;

  test = "|  a |  b | a + b |\n|  4 | 34 |    38 |\n| 21 | 31 |    52 |\n|  5 |  8 |    13 |\n#+TBLFM: $3=$1+$2\n\n* thing\n  1. test\n  2. two\n** subthing\n:RESULTS:\ntest\nblah blah\n:END:\n  3. three\n\n#+begin_src javascript\n  console.log('duh')\n  console.log('dur')\n#+end_src\n\n* TODO [#B] test [2/2]                                                       :duh:\n  - [X] one\n  - [X] two";

  node = parseOrgMode(test);

  console.log("TEXT: " + (node.toJson()));

  console.log("\n\nSAME: " + (node.allText() === test));

}).call(this);
